AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    0d646d4e-2b92-4cf1-934e-32b9916b8288:
      size:
        width: 60
        height: 60
      position:
        x: 340
        'y': 210
      z: 0
      embeds: []
      dependson:
        - 3a3b8709-3af5-489c-b7b6-517b18020438
    3a3b8709-3af5-489c-b7b6-517b18020438:
      size:
        width: 60
        height: 60
      position:
        x: 350
        'y': 110
      z: 0
      embeds: []
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: can contain only ASCII characters.
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-7f418316
    us-west-1:
      AMI: ami-951945d0
    us-west-2:
      AMI: ami-16fd7026
    eu-west-1:
      AMI: ami-24506250
    sa-east-1:
      AMI: ami-3e3be423
    ap-southeast-1:
      AMI: ami-74dda626
    ap-southeast-2:
      AMI: ami-b3990e89
    ap-northeast-1:
      AMI: ami-dcfa4edd
Resources:
  mys3bucket101autumnleaf:
    Type: 'AWS::S3::Bucket'
    Properties: 
     VersioningConfiguration:
        Status: Enabled
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d646d4e-2b92-4cf1-934e-32b9916b8288
    DependsOn:
      - myEC2instance101
  myEC2instance101:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      UserData: !Base64 '80'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3a3b8709-3af5-489c-b7b6-517b18020438
